# Generated by Django 2.2.6 on 2021-07-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['description'], name='description_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['published_at'], name='published_at_idx'),
        ),
    ]
